apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: manager-rbac
    {{- include "mcra.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - addondeploymentconfigs
    verbs:
      - '*'
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/status
    verbs:
      - patch
      - update
  - apiGroups:
      - appeng.ecosystem.redhat.com
    resources:
      - resilientclusterclaimbinding
    verbs:
      - '*'
  - apiGroups:
      - appeng.ecosystem.redhat.com
    resources:
      - resilientclusterclaimbinding/finalizer
    verbs:
      - '*'
  - apiGroups:
      - appeng.ecosystem.redhat.com
    resources:
      - resilientclusters
    verbs:
      - '*'
  - apiGroups:
      - appeng.ecosystem.redhat.com
    resources:
      - resilientclusters/finalizer
    verbs:
      - '*'
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - get
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    verbs:
      - approve
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hive.openshift.io
    resources:
      - clusterclaims
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - hive.openshift.io
    resources:
      - clusterclaims/finalizers
    verbs:
      - update
  - apiGroups:
      - hive.openshift.io
    resources:
      - clusterdeployments
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - hive.openshift.io
    resources:
      - clusterpools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - work.open-cluster-management.io
    resources:
      - manifestworks
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
