apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  labels:
    app.kubernetes.io/component: manager-workload
    {{- include "mcra.labels" . | nindent 4 }}
  name: multicluster-resiliency-addon
  namespace: {{ .Values.manager.namespace }}
spec:
  addOnMeta:
    description: TODO add description
    displayName: MultiCluster Resiliency Addon
  supportedConfigs:
    - defaultConfig:
        name: {{ .Chart.Name }}-deploy-config
        namespace: {{ .Values.manager.namespace }}
      group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
