apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager-workload
    {{- include "mcra.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-manager
  namespace: {{ .Values.manager.namespace }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: manager-workload
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: manager-workload
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - args:
            - manager
            - --agent-image={{ template "mcra.agent-image" . }}
            - --service-account={{ .Chart.Name }}-sa
            - --configmap_name={{ .Chart.Name }}-config
            - --controller-leader-election
            - --controller-probe-address=:8081
            - --controller-metric-address=127.0.0.1:8080
            - --enable-validation-webhook
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ template "mcra.manager-image" . }}
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
          {{- .Values.manager.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
        - args:
            - --secure-listen-address=0.0.0.0:8383
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: {{ .Values.manager.metrics.proxy.image }}
          name: kube-rbac-proxy
          ports:
            - containerPort: 8383
              name: https
              protocol: TCP
          resources:
          {{- .Values.manager.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Chart.Name }}-sa
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ .Chart.Name }}-webhook-server-cert
