apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    {{- include "mcra.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-metrics-service
  namespace: {{ .Values.manager.namespace }}
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
