apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: manager-rbac
    {{- include "mcra.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Values.manager.namespace }}
