apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Chart.Name }}-webhook-server-cert
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "mcra.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-webhook-service
  namespace: {{ .Values.manager.namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
