# Copyright (c) 2023 Red Hat, Inc.

# hive holds configuration for OpenShift Hive access
hive:
  # pool is the name of the global ClusterPool for claiming clusters from.
  pool: vp-pool

# manager holds configuration for the Addon Manager deployment running on the Hub
manager:
  image:
    registry: quay.io
    owner: ecosystem-appeng
    name: multicluster-resiliency-addon
    tag: devel
    pullPolicy: IfNotPresent
  namespace: open-cluster-management
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metrics:
    monitoring:
      namespace: openshift-monitoring
    proxy:
      image:
        registry: gcr.io
        owner: kubebuilder
        name: kube-rbac-proxy
        tag: v0.14.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 64Mi

# agent holds configuration for the Addon Agent deployment running on Spokes
agent:
  image:
    registry: quay.io
    owner: ecosystem-appeng
    name: multicluster-resiliency-addon
    tag: devel
    # TODO pull policy not yet implemented
    pullPolicy: IfNotPresent
  # TODO namespace not implemented yet
  namespace: open-cluster-management-agent-addon
  replicas: 1
  # TODO resources not yet implemented
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
